name: Build and deploy Docker containers to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: Build and push backend container
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/subnet-calculator-backend:${{ github.sha }}
          file: ./backend/Dockerfile

      - name: Build and push frontend container
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/subnet-calculator-frontend:${{ github.sha }}
          file: ./frontend/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'subnetting'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: |
            ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/subnet-calculator-backend:${{ github.sha }}
            ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/subnet-calculator-frontend:${{ github.sha }} 